ALTER TABLE users
    ALTER COLUMN role TYPE VARCHAR(20) USING role::VARCHAR;

ALTER TABLE jobs
    ALTER COLUMN status TYPE VARCHAR(20) USING status::VARCHAR,
    ALTER COLUMN job_type TYPE VARCHAR(20) USING job_type::VARCHAR,
    ALTER COLUMN experience_level TYPE VARCHAR(20) USING experience_level::VARCHAR;

ALTER TABLE applications
    ALTER COLUMN status TYPE VARCHAR(30) USING status::VARCHAR;

ALTER TABLE notifications
    ALTER COLUMN type TYPE VARCHAR(50) USING type::VARCHAR;
